version: "3.5"
services:
    api:
        image: "node:latest"
        container_name: "api"
        user: "node"
        working_dir: /home/node/api
        environment:
          - NODE_ENV=production
        volumes:
          - ./api:/home/node/api
        expose:
          - "8080"
        command: "npm start"
    proxy:
        image: nginx
        container_name: "proxy"
        ports:
          - "80:80"
        volumes:
          - ./nginx/conf.d/prod:/etc/nginx/conf.d
