version: "3.5"
services:
    api:
        image: "node:11"
        container_name: "api"
        working_dir: /home/node/api
        environment:
          - NODE_ENV=production
        volumes:
          - ./api:/home/node/api
          - node:/home/node/api/node_modules
        expose:
          - "8080"
        command: bash -c "npm install && npm start"
        restart: unless-stopped
    proxy:
        image: nginx
        container_name: "proxy"
        ports:
          - "80:80"
        volumes:
          - ./nginx/conf.d/prod:/etc/nginx/conf.d
        restart: unless-stopped
volumes:
    node:
